Handle Scenario Outlines with missing results
Sometimes the json formatter does not include results in step
elements of a Scenario Outline.
For example, see: https://github.com/cucumber/gherkin/issues/165

This caused an NPE when generating reports:

    org.apache.velocity.exception.MethodInvocationException: Invocation of
    method 'getName' in class net.masterthought.cucumber.json.Step threw
    exception java.lang.NullPointerException at
    templates/featureReport.vm[line 210, column 25]

This looks like a regression introduced in 906b9b92a12c5e4c8512b466ca725d2cb74e2653.